# Generated by Django 4.1.2 on 2022-10-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super_types", "0004_remove_supertype_super_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supertype",
            name="type",
        ),
        migrations.AddField(
            model_name="supertype",
            name="Hero",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="supertype",
            name="Villain",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
