# Generated by Django 4.1.2 on 2022-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super_types", "0005_remove_supertype_type_supertype_hero_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supertype",
            name="Hero",
        ),
        migrations.RemoveField(
            model_name="supertype",
            name="Villain",
        ),
        migrations.AddField(
            model_name="supertype",
            name="type",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
