# Generated by Django 4.1.2 on 2022-10-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="super",
            name="super_type",
        ),
    ]
